/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_meia;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author josue && pablo
 */
public class Login extends javax.swing.JFrame {

    static String Usuario;
    static String Password;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        lblinformacion = new javax.swing.JLabel();
        lblforgotpassword = new javax.swing.JLabel();
        lblnewuser = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 210, 30));

        lblinformacion.setForeground(new java.awt.Color(255, 255, 255));
        lblinformacion.setText("¿No tienes una cuenta? ");
        getContentPane().add(lblinformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        lblforgotpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblforgotpassword.setText("Olvidaste tu contraseña?");
        lblforgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblforgotpasswordMouseClicked(evt);
            }
        });
        getContentPane().add(lblforgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        lblnewuser.setForeground(new java.awt.Color(255, 255, 255));
        lblnewuser.setText("Crea una");
        lblnewuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnewuserMouseClicked(evt);
            }
        });
        getContentPane().add(lblnewuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, 30));

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 210, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_meia/LOGO_MEIA2 .png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void lblforgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblforgotpasswordMouseClicked
        ReestablecerPassword PassUser = new ReestablecerPassword();
        PassUser.setLocationRelativeTo(null);
        PassUser.show();
        this.dispose();
    }//GEN-LAST:event_lblforgotpasswordMouseClicked

    private void lblnewuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnewuserMouseClicked
        Nuevo_Usuario NewUser = new Nuevo_Usuario();
        NewUser.setLocationRelativeTo(null);
        NewUser.show();
        this.dispose();
    }//GEN-LAST:event_lblnewuserMouseClicked

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

        String Password = txtpassword.getText();
        String User = txtuser.getText();
        
        if (ExisteArchivo("C:\\MEIA\\Bitacora_Usuarios.txt"))
        {
            try 
            {
                boolean Existe;
                Existe = ValidarPassword(User,Password);
                
                if (Existe)
                {
                    Principal Menu = new Principal(User);
                    Menu.setLocationRelativeTo(null);
                    Usuario = User;
                    Menu.show();
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "Error\n"
                            + "El usuario o contraseña ingresados no son validos\n"
                            + "Intenta de nuevo");
            }
            catch (IOException ex) 
            {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "En este momento aun no existe ningun usuario registrado por lo "
                    + "que tu seras registrado como administrador. \n"
                    + "Unicamente debes de ingresar tu informacion en la siguiente ventana");
            
            Nuevo_Usuario NewUser = new Nuevo_Usuario();
            NewUser.setLocationRelativeTo(null);
            NewUser.show();
            this.dispose();
        }

    }//GEN-LAST:event_btnloginActionPerformed

    // Metodo que verifica si existe el archivo de usuarios
    private boolean ExisteArchivo(String path)
    {
        String pathRuta = path;
        File Archivo = new File(pathRuta);
        
        if (Archivo.exists())
            return true;
        else
            return false;
    }
    
    // Método que verifica si el usuario y contraseña ingresados son correctos
    private boolean ValidarPassword(String User, String Password) throws FileNotFoundException, IOException
    {
        boolean Hallazgo = false;
        String pathRuta = "C:\\MEIA\\Bitacora_Usuarios.txt";
        
        File Archivo = new File(pathRuta);
        
        FileReader Leer = new FileReader(Archivo);
        BufferedReader leerArchivo = new BufferedReader(Leer);
        String Linea = leerArchivo.readLine();

        while(Linea != null)
        {
            if(Linea.contains(User) && Linea.contains(Password))
                Hallazgo = true;
            
            Linea = leerArchivo.readLine();
        } 
        leerArchivo.close();
        Leer.close();

        return Hallazgo;
    }
    
    public String UsuarioLogeado()
    {
        return Usuario;
    }
    
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblforgotpassword;
    private javax.swing.JLabel lblinformacion;
    private javax.swing.JLabel lblnewuser;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
