/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_meia;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Modificacion_De_Listas extends javax.swing.JFrame {

    /**
     * Creates new form Modificacion_De_Listas
     */
    
    static String NombreLista;
    static String Usuario;
      
    public Modificacion_De_Listas(String Dato, String Usuario) throws IOException {
        
        NombreLista = Dato;
        lblLista.setText("Lista:"+NombreLista);
        BuscarListas(Usuario);
        initComponents();
    }
    
     public Modificacion_De_Listas() {
     
     }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuariosLista = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificacion de Listas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 440, -1));

        btnRegresar.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnRegresar.setText("Regresar");
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 120, 30));

        lblLista.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lblLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLista.setText("Lista: Nombre de la Lista");

        jScrollPane1.setViewportView(lstUsuariosLista);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese el nombre del Usuario a buscar");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seleccione un Usuario para agregar a la Lista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblLista)
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreUsuario)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 730, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_meia/Fondo1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //En esta Funcion se Buscan las Listas para llenar La Lista del Menu Principal.
    private void BuscarListas(String Usuario) throws FileNotFoundException, IOException
    {
        if(Usuario == "Administrador")
        {
            String pathRuta = "C:\\MEIA\\ListaUsuario.txt";
            File Archivo = new File(pathRuta);
            
            if(Archivo.exists())
            {
            FileReader Lectura = new FileReader(Archivo);
            BufferedReader Leer = new BufferedReader(Lectura);
            String Linea = Leer.readLine();
            String[] Auxiliar;
            List<Lista> Listas = new ArrayList<Lista>();
            Lista NuevaLista;
            
            while(Linea != null)
            {
              Auxiliar = Linea.split("\\|"); 
              NuevaLista = new Lista(Auxiliar[0],Auxiliar[1],Auxiliar[2],Auxiliar[3],Auxiliar[4],Auxiliar[5]);
              Listas.add(NuevaLista);
            }
            
            DefaultListModel Modelo = new DefaultListModel();
            Modelo.addElement("Nombre Lista:    "+ "Usuario:    "+"Usuario Asociado:    "+"Descripcion:    "+"Fecha de Creacion:    "+"Estatus    ");
            for(int i = 0; i< Listas.size(); i++)
            {
                Modelo.addElement(Listas.get(i).Nombre_lista+" "+Listas.get(i).Usuario+" "+Listas.get(i).Descripcion+" "+Listas.get(i).Numero_usuarios+" "+Listas.get(i).Fecha_creacion+" "+Listas.get(i).Status);
            }
            lstUsuariosLista.setModel(Modelo);
            }
            else
            {
            pathRuta = "C:\\MEIA\\Bitacora_ListaUsuario.txt";
            Archivo = new File(pathRuta);
            FileReader Lectura = new FileReader(Archivo);
            BufferedReader Leer = new BufferedReader(Lectura);
            String Linea = Leer.readLine();
            String[] Auxiliar;
            List<Lista> Listas = new ArrayList<Lista>();
            Lista NuevaLista;
            
            while(Linea != null)
            {
              Auxiliar = Linea.split("\\|"); 
              NuevaLista = new Lista(Auxiliar[0],Auxiliar[1],Auxiliar[2],Auxiliar[3],Auxiliar[4],Auxiliar[5]);
              Listas.add(NuevaLista);
            }
            
            DefaultListModel Modelo = new DefaultListModel();
            Modelo.addElement("Nombre Lista:    "+ "Usuario:    "+"Usuario Asociado:    "+"Descripcion:    "+"Fecha de Creacion:    "+"Estatus    ");
            for(int i = 0; i< Listas.size(); i++)
            {
                Modelo.addElement(Listas.get(i).Nombre_lista+" "+Listas.get(i).Usuario+" "+Listas.get(i).Descripcion+" "+Listas.get(i).Numero_usuarios+" "+Listas.get(i).Fecha_creacion+" "+Listas.get(i).Status);
            }
            lstUsuariosLista.setModel(Modelo);
            }
            
        }else
        {
            String pathRuta = "C:\\MEIA\\ListaUsuario.txt";
            File Archivo = new File(pathRuta);
            if(Archivo.exists())
            {
            FileReader Lectura = new FileReader(Archivo);
            BufferedReader Leer = new BufferedReader(Lectura);
            String Linea = Leer.readLine();
            String[] Auxiliar;
            List<Lista> Listas = new ArrayList<Lista>();
            Lista NuevaLista;
            
            while(Linea != null)
            {
              Auxiliar = Linea.split("\\|"); 
              NuevaLista = new Lista(Auxiliar[0],Auxiliar[1],Auxiliar[2],Auxiliar[3],Auxiliar[4],Auxiliar[5]);
              if(Auxiliar[1].equals(Usuario))
              Listas.add(NuevaLista);
            }
            
            DefaultListModel Modelo = new DefaultListModel();
            Modelo.addElement("Nombre Lista:    "+ "Usuario:    "+"Usuario Asociado:    "+"Descripcion:    "+"Fecha de Creacion:    "+"Estatus    ");
            for(int i = 0; i< Listas.size(); i++)
            {
                Modelo.addElement(Listas.get(i).Nombre_lista+"|"+Listas.get(i).Usuario+"|"+Listas.get(i).Descripcion+"|"+Listas.get(i).Numero_usuarios+"|"+Listas.get(i).Fecha_creacion+"|"+Listas.get(i).Status);
            }
            lstUsuariosLista.setModel(Modelo);  
            }
            else
            {
            pathRuta = "C:\\MEIA\\Bitacora_ListaUsuario.txt";
            Archivo = new File(pathRuta);   
            FileReader Lectura = new FileReader(Archivo);
            BufferedReader Leer = new BufferedReader(Lectura);
            String Linea = Leer.readLine();
            String[] Auxiliar;
            List<Lista> Listas = new ArrayList<Lista>();
            Lista NuevaLista;
            
            while(Linea != null)
            {
              Auxiliar = Linea.split("\\|"); 
              NuevaLista = new Lista(Auxiliar[0],Auxiliar[1],Auxiliar[2],Auxiliar[3],Auxiliar[4],Auxiliar[5]);
              if(Auxiliar[1].equals(Usuario))
              Listas.add(NuevaLista);
            }
            
            DefaultListModel Modelo = new DefaultListModel();
            Modelo.addElement("Nombre Lista:    "+ "Usuario:    "+"Usuario Asociado:    "+"Descripcion:    "+"Fecha de Creacion:    "+"Estatus    ");
            for(int i = 0; i< Listas.size(); i++)
            {
                Modelo.addElement(Listas.get(i).Nombre_lista+"|"+Listas.get(i).Usuario+"|"+Listas.get(i).Descripcion+"|"+Listas.get(i).Numero_usuarios+"|"+Listas.get(i).Fecha_creacion+"|"+Listas.get(i).Status);
            }
            lstUsuariosLista.setModel(Modelo); 
            }
        }
    }
    
    //En esta Funcion se Buscan las Listas para llenar La Lista del Menu Principal.
    private boolean ListaExiste(String NombreLista,String Usuario) throws FileNotFoundException, IOException
    {
            String pathRuta = "C:\\MEIA\\ListaUsuario.txt";
            File Archivo = new File(pathRuta);
            boolean Existe = false;
            
            if(Archivo.exists())
            {
            FileReader Lectura = new FileReader(Archivo);
            BufferedReader Leer = new BufferedReader(Lectura);
            String Linea = Leer.readLine();
            String[] Auxiliar;
            
            while(Linea != null)
            {
              Auxiliar = Linea.split("\\|"); 
              if(Auxiliar[1].equals(Usuario) && Auxiliar[0].equals(NombreLista))
              Existe = true;
            }
            
            }
            else
            {
            String pathRutax = "C:\\MEIA\\Bitacora_ListaUsuario.txt";
            File Archivox = new File(pathRutax);
            FileReader Lecturax = new FileReader(Archivox);
            BufferedReader Leerx = new BufferedReader(Lecturax);
            String Lineax = Leerx.readLine();
            String[] Auxiliarx;
            
            while(Lineax != null)
            {
              Auxiliarx = Lineax.split("\\|"); 
              if(Auxiliarx[1].equals(Usuario) && Auxiliarx[0].equals(NombreLista))
              Existe = true;
            }
            }
            
            return Existe;
    }
    
    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        
        
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      
        String Nombre = txtNombreUsuario.getText();
        try {
            if(ListaExiste(NombreLista,Nombre) == true)
            {
                JOptionPane.showMessageDialog(this,"El Nombre de Usuario que Busca SI Existe","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this,"El Nombre de Usuario que Busca NO Existe","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        String Cadena = lstUsuariosLista.getSelectedValue();
        String []ArregloCadena = Cadena.split("\\|");
        String Nombre = ArregloCadena[0];
        String Usuario = ArregloCadena[1];
        Procesos TamañoFijo = new Procesos();
        if(Cadena != "")
        {
        try {
            String pathRuta = "C:\\MEIA\\ListaUsuario.txt";
            File Archivo = new File(pathRuta);
            RandomAccessFile ArchivoSustitucion = new RandomAccessFile(Archivo,"rw");
            String Linea = ArchivoSustitucion.readLine();
            String [] Auxiliar;
         
               
            while(Linea != null)
            {
                Auxiliar = Linea.split("\\|"); 
                if(Auxiliar[0].equals(Nombre) && Auxiliar[1].equals(Usuario))
                {
                    Lista NuevaLista = new Lista(TamañoFijo.RellenarCaracteres(ArregloCadena[0], 1),TamañoFijo.RellenarCaracteres(ArregloCadena[1], 0), TamañoFijo.RellenarCaracteres(ArregloCadena[2], 2),ArregloCadena[3], ArregloCadena[4], "0");
                    String Sustitucion = NuevaLista.Nombre_lista+"|"+NuevaLista.Usuario+"|"+NuevaLista.Descripcion+"|"+NuevaLista.Numero_usuarios+"|"+NuevaLista.Fecha_creacion+"|"+NuevaLista.Status;
                    ArchivoSustitucion.writeBytes(Sustitucion);
                }
                Linea = ArchivoSustitucion.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Listas.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun elemento");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       //Programar Agregar
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //Programar ComboBox
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificacion_De_Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificacion_De_Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificacion_De_Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificacion_De_Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificacion_De_Listas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLista;
    private javax.swing.JList<String> lstUsuariosLista;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
