
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto_meia.BDD;
import proyecto_meia.EnviarMensaje;
import proyecto_meia.Principal;
import proyecto_meia.Procesos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josue
 */
public class EnviarMensajeRed extends javax.swing.JFrame {

    /**
     * Creates new form EnviarMensajeRed
     */
    
    Procesos procesos = new Procesos();
    
    private String Usuario;
    private String Rol;
    
    public EnviarMensajeRed(String usuario, String rol) {
        initComponents();
        this.Usuario = usuario;
        this.Rol = rol;
    }

    private EnviarMensajeRed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblEncabezado = new javax.swing.JLabel();
        JlblNombre = new javax.swing.JLabel();
        jCBDestinatario = new javax.swing.JComboBox<>();
        jTFAsunto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblPara2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAMensaje = new javax.swing.JTextArea();
        jBtnDescartar = new javax.swing.JButton();
        jBtnEnviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLblPara1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Enviar Mensaje");
        getContentPane().add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        JlblNombre.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        JlblNombre.setForeground(new java.awt.Color(255, 255, 255));
        JlblNombre.setText("Nombre del Usuario");
        getContentPane().add(JlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jCBDestinatario.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jCBDestinatario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jCBDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDestinatarioActionPerformed(evt);
            }
        });
        getContentPane().add(jCBDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 40, -1));

        jTFAsunto.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jTFAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAsuntoActionPerformed(evt);
            }
        });
        getContentPane().add(jTFAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 570, -1));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Asunto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLblPara2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLblPara2.setForeground(new java.awt.Color(255, 255, 255));
        jLblPara2.setText("Grupo");
        getContentPane().add(jLblPara2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 360, -1));

        jTAMensaje.setColumns(20);
        jTAMensaje.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jTAMensaje.setLineWrap(true);
        jTAMensaje.setRows(5);
        jTAMensaje.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTAMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 570, 180));

        jBtnDescartar.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jBtnDescartar.setText("Descartar");
        jBtnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDescartarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jBtnEnviar.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jBtnEnviar.setText("Enviar");
        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_meia/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        jLblPara1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLblPara1.setForeground(new java.awt.Color(255, 255, 255));
        jLblPara1.setText("Grupo");
        getContentPane().add(jLblPara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAsuntoActionPerformed

    private void jCBDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDestinatarioActionPerformed

    private void jBtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed

       int idGrupoReceptor = Integer.parseInt(jCBDestinatario.getSelectedItem().toString());
       String Receptor = txtNombre.toString();
       String Asunto = jTFAsunto.toString();
       String Mensaje = jTAMensaje.toString();
       Date Fecha = new Date();
       
        try {
            BDD.getInstancia().Insert(1, idGrupoReceptor,Usuario,Receptor,Asunto, Mensaje);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EnviarMensajeRed.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EnviarMensajeRed.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "El Correo Ha Sido Enviado");
    }//GEN-LAST:event_jBtnEnviarActionPerformed

    private void jBtnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDescartarActionPerformed

        Principal Menu;
        try
        {
            Menu = new Principal(Usuario, Rol);
            Menu.setLocationRelativeTo(null);
            Menu.show();
            this.dispose();
        }
        catch (IOException ex)
        {
            Logger.getLogger(EnviarMensaje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnDescartarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarMensajeRed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarMensajeRed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarMensajeRed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarMensajeRed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarMensajeRed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblNombre;
    private javax.swing.JButton jBtnDescartar;
    private javax.swing.JButton jBtnEnviar;
    private javax.swing.JComboBox<String> jCBDestinatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblPara1;
    private javax.swing.JLabel jLblPara2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAMensaje;
    private javax.swing.JTextField jTFAsunto;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
